[package]
name = "aether-common"
edition = "2021"
version.workspace = true
license.workspace = true
publish = false

[dependencies]
tokio = { version = "1.0", features = ["sync"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"
